apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-video-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-video
  template:
    metadata:
      labels:
        app: nginx-video
    spec:
      containers:
        - name: nginx
          image: nginx-video-streaming
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/share/nginx/html/videos
              name: videos-volume
            - mountPath: /usr/share/nginx/html/stream
              name: stream-volume
      volumes:
        - name: videos-volume
          hostPath:
            path: /home/docker/proba/videos  # Ruta absoluta en tu host
            type: Directory
        - name: stream-volume
          emptyDir: {}
