apiVersion: apps/v1  # ¡Versión de la API es obligatoria!
kind: Deployment
metadata:
  name: nginx-video-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-video
  template:
    metadata:
      labels:
        app: nginx-video
    spec:
      containers:
      - name: nginx
        image: nginx-video-streaming
        imagePullPolicy: Never  # Usar la imagen local
        ports:
        - containerPort: 80
